export const images = {
  sing_in_banner: require('src/assets/img/sing_in_banner.png'),
  books: require('src/assets/img/books.png'),
  catalog_banner: require('src/assets/img/catalog_banner.png'),
  books_favorite: require('src/assets/img/books_fav.png'),
  user_logo: require('src/assets/img/userlogo.png'),
  camera_button: require('src/assets/img/button_photo.png'),
  mail_grey: require('src/assets/img/Mail_disabled.png'),
  user_grey: require('src/assets/img/userprofile.png'),
  open_eye: require('src/assets/img/View.png'),
  closed_eye: require('src/assets/img/Hide.png'),
  picture_auth: require('src/assets/img/personLogin.png'),
  button_heart_saved: require('src/assets/img/button_save_active.png'),
  button_heart: require('src/assets/img/button_save.png'),
  logo_white: require('src/assets/img/logo_white.png'),
  search_icon: require('src/assets/img/Search.png'),
  star: require('src/assets/img/Star.png'),
  star_less: require('src/assets/img/star_less.png'),
  human_going: require('src/assets/img/humanGoing.png'),
  onboarding_book: require('src/assets/img/onboarding_book.png'),
};
